image:
  registry: docker.io
  repository: bitnamilegacy/keycloak
  tag: 26.3.3-debian-12-r0

auth:
  adminUser: admin
  existingSecret: "keycloak-secret"

adminRealm: "master"

httpEnabled: false

service:
  type: ClusterIP

  http:
    enabled: true

  ports:
    http: 80

postgresql:
  enabled: true

  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: 15.9.0-debian-12-r0

  auth:
    username: bn_keycloak
    database: bitnami_keycloak
    existingSecret: keycloak-db-secret
    secretKeys:
      userPasswordKey: password
  architecture: standalone

httpRelativePath: "/"

ingress:
  enabled: true
  pathType: Prefix
  hostname: keycloak.com
  ingressClassName: "traefik"
  controller: default
  path: "{{ .Values.httpRelativePath }}"
  servicePort: http
  annotations: 
    cert-manager.io/cluster-issuer: ca-cluster-issuer
  tls: true